### PR TITLE
Fixes remaining "ts" parameters from number to string type

### PR DESCRIPTION
**Pull request by jeremeamia**
Fixes remaining "ts" parameters from `number` type to `string` type. Similar issues reported for other parameters in #12, #22, #26, #27, and #75. Also adds the phpunit result cache file to gitignore list.

### CODE REVIEW

**Comment by jeremeamia** [comment]
@damienalexandre It's unclear how to get the tests to run correctly. I appreciate any help with that and for considering this change. Thanks.

**Comment by damienalexandre** [comment]
Hi, thanks for your PR! Looks like there is an issue with our TravisCI configuration, I will have a look.

**Comment by damienalexandre** [comment]
The tests are RED here because they are not run correctly on forks (secret variables are not exposed to avoid leak). Sorry about that.

Also your PR is incomplete, can you push the new generated code too? You have to follow those steps: 

https://github.com/jolicode/slack-php-api/blob/master/doc/updating-sdk.md#regenerate-the-sdk

Thanks!

**Comment by jeremeamia** [comment]
Added the newly generated bits.

**Comment by damienalexandre** [comment]
Thanks @jeremeamia! I'm going to add some tests and publish a release today.

**Comment by jeremeamia** [comment]
Thanks @damienalexandre!

**Pull request merged**
