### PR TITLE
added title and pretext field in ObjsMessageAttachmentsItem

### PR DESCRIPTION
**Pull request by binary111**

### CODE REVIEW

**Comment by pyrech** [comment]
Hello 🙂 

Thanks for your contribution but sadly I cannot accept It right now. This PHP client is generated automatically from the OpenAPI spec, so you should not edit the classes on the `generated` directory, as stated in their phpdoc.

Please have a look at the documentation on how to update the sdk: https://github.com/jolicode/slack-php-api/blob/master/doc/updating-sdk.md#updating-the-sdk

Thanks

**Comment by damienalexandre** [comment]
The OpenAPI Specification is not always up to date, and they say it's very complicated for them to generate it.

I think we should use a patch mechanism while waiting for updates on Slack side.

For example we already edited the specification here: f97f5cdf6d65be8e9d20639c8ad4994447f29864 :fearful: 

What we could do:

- restore https://api.slack.com/specs/openapi/v2/slack_web.json to it's initial state in the repo;
- create a new folder with ".patch" files in a diff format;
- apply the patch just before running the generator.

**Comment by pyrech** [comment]
I really like the patch idea. We just need to handle with care diffs that could conflict in the future when Slack update their spec.

**Comment by pyrech** [comment]
Hello @binary111 :slightly_smiling_face: 
Now that the way to update the SDK has changed in #11, would you mind to update your PR according to [this documentation](https://github.com/jolicode/slack-php-api/blob/master/doc/updating-sdk.md)?
Thanks

**Comment by damienalexandre** [comment]
Fixed in #17 - thanks for pointing this up!

**Pull request closed without merging**
