### PR TITLE
Add team_id support for 3 endpoints

### LINKED ISSUE #137: UsersList and UsergroupsList should accept new parameter: "team_id"
API specs with JSON schema do not contain parameter "team_id":

- https://github.com/slackapi/slack-api-specs/blob/bc08db49625630e3585bf2f1322128ea04f2a7f3/web-api/slack_web_openapi_v2_without_examples.json#L21888-L21913
- https://github.com/slackapi/slack-api-specs/blob/bc08db49625630e3585bf2f1322128ea04f2a7f3/web-api/slack_web_openapi_v2_without_examples.json#L20546-L20572

but it appears on official Web documentation:

- https://api.slack.com/methods/users.list 
- https://api.slack.com/methods/usergroups.list 

-----

Currently I'm patching like this :(

```php
$response = $this->client->executeEndpoint(new class ($params) extends Endpoint\UsersList {
    protected function getQueryOptionsResolver(): OptionsResolver
    {
        $resolver = parent::getQueryOptionsResolver();
        $resolver->define('team_id');
        $resolver->setAllowedTypes('team_id', ['string']);

        return $resolver;
    }
});
```

```php
$response = $this->client->executeEndpoint(new class ($params) extends Endpoint\UsergroupsList {
    protected function getQueryOptionsResolver(): OptionsResolver
    {
        $resolver = parent::getQueryOptionsResolver();
        $resolver->define('team_id');
        $resolver->setAllowedTypes('team_id', ['string']);

        return $resolver;
    }
});
```

### PR DESCRIPTION
**Pull request by mpyw**
- Fixes #137
- Closes #129

### CODE REVIEW

**Comment by mpyw** [comment]
@damienalexandre Hi, there are some problems:

- `./bin/slack-api-client-generator spec:update` partially fails and it generates `*.rej` file with changes which make **some `token` parameter required.**
- `vendor/bin/jane-openapi generate --config-file=.jane-openapi.php` gives no effect on SDK about `team_id`.

They look wrong, what should I do next?

**Comment by damienalexandre** [comment]
Hey!

I think something went wrong, I tried it locally and it was fine, here is what I did:

```sh
# get your first commit
git cherry-pick 5f17c6f
# remove existing SDK
rm -Rf generated/*
# build new SDK with team ID
vendor/bin/jane-openapi generate --config-file=.jane-openapi.php
# run the tests and check the code (team id is here!)
vendor/bin/simple-phpunit
# update the patch file automatically
./bin/slack-api-client-generator spec:generate-patch
# check the patch is valid
./bin/slack-api-client-generator spec:update
```

That's it - you can then just commit the result.

**Comment by mpyw** [comment]
@damienalexandre Thanks for the heads up! It is ready for review now

**Comment by damienalexandre** [comment]
Looks good now! Thanks a lot for this contribution, that helps a lot :yum:

**Pull request merged**
